### ISSUE TITLE
Share game url copy button is not working

### ISSUE THREAD

**Issue by platput** [platput/filmemo#22]

**Comment by kiozet** [comment]
Hey, buddy! Could you give us a little more information? Do we need to look in CreateGame.vue (func add player) and PlayersList.vue?

**Comment by platput** [comment]
Hey, thanks for showing interest. The share game button and text area is in a component: https://github.com/platput/filmemo/blob/main/filmemo-ui/src/components/ShareGame.vue

Currently it is working when locally tested but in production it is not.

**Comment by platput** [comment]
I have figured out the issue and I am trying to fix it. The clipboard api will not work if the page is not served through https. So I am converting the site to use https and it will most likely solve the issue. Will keep this thread updated.

**Comment by kiozet** [comment]
Got it. Did this solve your problem?

> I have figured out the issue and I am trying to fix it. The clipboard api will not work if the page is not served through https. So I am converting the site to use https and it will most likely solve the issue. Will keep this thread updated.

**Comment by platput** [comment]
Yes, I was using aws s3 to serve the front end which doesn't have https.
For https we can add cloudfront and that solved the issue. Thanks for asking.
